### ISSUE TITLE
Add PressThis

### ISSUE THREAD

**Issue by dartiss** [dartiss/restore-lost-functionality#6]
https://wordpress.org/plugins/press-this/

**Comment by kraftbj** [comment]
The bookmarklet itself was re-added via the plugin, so as long as restore-lost-functionality can facilitate installing the plugin, everything will be as before. Since WP itself handles that when visiting wp-admin/press-this.php, I'm not sure how needed it is though.

**Comment by dartiss** [comment]
A good point. Really just noted it here to look into it a later time.

The plugin does, though, facilitate installing the plugin, so many are just listing for plugins to make it easier to find them. However, I'll have a play with the current process to see if it's worth adding or not.

**Comment by dartiss** [comment]
Added to #10
